---
title: "newton"
author: "YunranChen"
date: "5/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("statmod")
library("statmod")
library(purrr)
library(dplyr)
library(magrittr)
library(ggplot2)
library(tidyr)
theme_set(theme_bw())
#install.packages("truncdist")
library(truncdist)
library(rbenchmark)
rm(list=ls())
```

## decide the range for x according to rule-of-thumb

```{r}
x_range=function(xs_vec,ntheta,l,u){
  n=length(xs_vec)
  bw_cut=sd(xs_vec)*(4/3/n)^(1/5)*3
  ub=max(xs_vec)+bw_cut
  lb=min(xs_vec)-bw_cut
  xxs=seq(max(lb,l),min(ub,u),length.out = ntheta)
  return(xxs)
}
```

```{r}
rtgamma=function(size,shape_,rate_,a,b){
  u=runif(n = size)
  c_inv=pgamma(q = b,shape = shape_,rate = rate_)-pgamma(q = a,shape = shape_,rate = rate_)
  x=qgamma(p = u*c_inv+pgamma(q=a,shape=shape_,rate=rate_,shape=shape_,rate = rate_)
  return(x)
}
dtgamma=function(x_,shape_,rate_,a,b){
  c_inv=pgamma(q = b,shape = shape_,rate = rate_)-pgamma(q = a,shape = shape_,rate = rate_)
  x=dgamma(x = x_,shape=shape_,rate = rate_)/c_inv
  return(x)
}
```

# truncated gamma + point mass mixture -- possion

$f(\theta) = \frac{1}{2}\delta_{10}+\frac{1}{2}Gamma_{[0,10]}(2,0.4)$

## Data Preparation

```{r}

## try truncated gamma + point mass mixture -- possion
N=100 #size for sample
n=200 #size for each sample
set.seed(123)

gpp_sampler_=function(size_,pi){
  xs_g=vector(length = size_)
  components = sample(1:2,prob=c(pi,1-pi),size=size_,replace=TRUE)
  xs_g[components==1]=10
  xs_g[components==2]=rtgamma(size =  sum(components==2),shape_ = 2,rate_ = 0.4,a = 0,b=10)
  xs_gp=map_dbl(xs_g,~rpois(n = 1,lambda = .x))
return(xs_gp)
}
Xs_bn=sapply(1:N,function(x){gpp_sampler_(n,0.5)})%>%t()
#Each row is a sample
```

## Predictive Recursive


```{r}

PR_GPP_uni=function(Xs_bn,a,b,pi,theta0,nGQ,ntheta){

N=nrow(Xs_bn)
n=ncol(Xs_bn)
#guass.quad
out=gauss.quad(nGQ)
xs_gq=out$nodes*(b-a)/2+(a+b)/2 #change interval
theta=seq(a,b,length.out = ntheta)

## Initial Guess: Uniform on [0,10]

p=rep(1/(b-a)/2,ntheta) #uniform
#p=dbeta(x = seq(0,1,length.out = ntheta),shape1 = c,shape2 = c)/(b-a)/2
ind0=ceiling((theta0-a)/((b-a)/ntheta))
p[ind0]=1/2

## weight seq
w=1/(1:n+1)

##Recursion
pr=function(i,p_0){
  p=p_0
  py=0
for (j in 1:n){
  p_x=map_dbl(theta,~dpois(x = Xs_bn[i,j],lambda = .x))
  int=((b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x = Xs_bn[i,j],lambda = .x))*p[ceiling((xs_gq-a)/((b-a)/ntheta))]))*(1-p[ind0])+p[ind0]*dpois(x = Xs_bn[i,j],lambda = theta0)
  p=(1-w[j])*p+w[j]*p_x*p/int
  py=log(int)+py
}
  return(list(p=p,py=py))
}
res_t=map(1:N,~pr(.x,p))
res=sapply(res_t,function(res_t){return(res_t$p)})
res_py=map_dbl(res_t,~.x$py)%>%exp(.)
#res=sapply(1:N,function(i){return(pr(i,p))})

##draw f(theta)
colnames(res)=paste0("est",1:N)
true_f=dtgamma(x_ = theta,shape_ = 2,rate_=0.4,a = a,b=b)*(1-pi)
true_f[ind0]=pi
res_f=res
for (col in 1:ncol(res)){
  res_f[-ind0,col]=(1-res[ind0,col])*res[-ind0,col]
}
ggdf=res_f%>%as_tibble()%>%
  mutate(x=theta,true=true_f)%>%
  gather(data = .,key=estimation,value=p,-x)
plotme_f=ggplot(data=ggdf,mapping = aes(x=x,y=p,group=estimation))+geom_point(colour = "grey",alpha=0.7)+geom_point(data=ggdf%>%filter(estimation=="true"),mapping = aes(x=x,y=p))+ggtitle(paste0("Gamma(2,0.4)[0,10]+Delta_10+Poisson_",ntheta))##+ggtitle("Gamma(2,0.4)[0,10]+Delta_10+Poisson")#


## get the p(x) -- Using Guassian Quadratic

Xss=apply(Xs_bn, 1, function(x){x_range(xs_vec = x,ntheta = ntheta,l = 0,u = Inf)})

xs=sapply(1:N,function(j){
  map_dbl(.x = Xss[,j],.f = function(xs_j){
    (b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x=round(xs_j),lambda = .x))*res[,j][ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-res[,j][ind0])+res[,j][ind0]*dpois(x = round(xs_j),lambda = theta0)
  })
  
})

true_xs=x_range(xs_vec = as.vector(Xs_bn),ntheta = ntheta,l = 0,u = Inf)
true=map_dbl(.x = true_xs,
             .f =function(xxs_i){ p=(b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x = round(xxs_i),lambda = .x))*(dtgamma(x_ = theta,shape_ = 2,rate_ = 0.4,a = a,b = b))[ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-pi)+pi*dpois(x = round(xxs_i),lambda = theta0)
             })

ggdf_p=data_frame(x=c(as.vector(Xss),true_xs)%>%round(.),p=c(as.vector(xs),true),estimation=c(paste0("est",rep(1:N,each=ntheta)),rep("true",ntheta)))
plotme_p=ggplot(data=ggdf_p,mapping = aes(x=x,y=p,group=estimation))+geom_line(colour = "grey",alpha=0.7)+geom_line(data=ggdf_p%>%filter(estimation=="true"),mapping = aes(x=x,y=p))+ggtitle(paste0("Gamma(2,0.4)[0,10]+Delta_10+Poisson_",ntheta))#+ggtitle("Gamma(2,0.4)[0,10]+Delta_10+Poisson")


return(list(result=res[ind0,],f=plotme_f,p=plotme_p,py=res_py))
}

PR_GPP_beta=function(Xs_bn,a,b,c,pi,theta0,nGQ,ntheta){

N=nrow(Xs_bn)
n=ncol(Xs_bn)
#guass.quad
out=gauss.quad(nGQ)
xs_gq=out$nodes*(b-a)/2+(a+b)/2 #change interval
theta=seq(a,b,length.out = ntheta)

## Initial Guess: Uniform on [0,10]

#p=rep(1/(b-a)/2,ntheta) #uniform
p=dbeta(x = seq(0,1,length.out = ntheta),shape1 = c,shape2 = c)/(b-a)/2
ind0=ceiling((theta0-a)/((b-a)/ntheta))
p[ind0]=1/2

## weight seq
w=1/(1:n+1)

##Recursion
pr=function(i,p_0){
  p=p_0
  py=0
for (j in 1:n){
  p_x=map_dbl(theta,~dpois(x = Xs_bn[i,j],lambda = .x))
  int=((b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x = Xs_bn[i,j],lambda = .x))*p[ceiling((xs_gq-a)/((b-a)/ntheta))]))*(1-p[ind0])+p[ind0]*dpois(x = Xs_bn[i,j],lambda = theta0)
  p=(1-w[j])*p+w[j]*p_x*p/int
  py=log(int)+py
}
  return(list(p=p,py=py))
}
res_t=map(1:N,~pr(.x,p))
res=sapply(res_t,function(res_t){return(res_t$p)})
res_py=map_dbl(res_t,~.x$py)%>%exp(.)
#res=sapply(1:N,function(i){return(pr(i,p))})

##draw f(theta)
colnames(res)=paste0("est",1:N)
true_f=dtgamma(x_ = theta,shape_ = 2,rate_=0.4,a = a,b=b)*(1-pi)
true_f[ind0]=pi
res_f=res
for (col in 1:ncol(res)){
  res_f[-ind0,col]=(1-res[ind0,col])*res[-ind0,col]
}
ggdf=res_f%>%as_tibble()%>%
  mutate(x=theta,true=true_f)%>%
  gather(data = .,key=estimation,value=p,-x)
plotme_f=ggplot(data=ggdf,mapping = aes(x=x,y=p,group=estimation))+geom_point(colour = "grey",alpha=0.7)+geom_point(data=ggdf%>%filter(estimation=="true"),mapping = aes(x=x,y=p))+ggtitle(paste0("Gamma(2,0.4)[0,10]+Delta_10+Poisson_",ntheta))##+ggtitle("Gamma(2,0.4)[0,10]+Delta_10+Poisson")#


## get the p(x) -- Using Guassian Quadratic

Xss=apply(Xs_bn, 1, function(x){x_range(xs_vec = x,ntheta = ntheta,l = 0,u = Inf)})

xs=sapply(1:N,function(j){
  map_dbl(.x = Xss[,j],.f = function(xs_j){
    (b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x=round(xs_j),lambda = .x))*res[,j][ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-res[,j][ind0])+res[,j][ind0]*dpois(x = round(xs_j),lambda = theta0)
  })
  
})

true_xs=x_range(xs_vec = as.vector(Xs_bn),ntheta = ntheta,l = 0,u = Inf)
true=map_dbl(.x = true_xs,
             .f =function(xxs_i){ p=(b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x = round(xxs_i),lambda = .x))*(dtgamma(x_ = theta,shape_ = 2,rate_ = 0.4,a = a,b = b))[ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-pi)+pi*dpois(x = round(xxs_i),lambda = theta0)
             })

ggdf_p=data_frame(x=c(as.vector(Xss),true_xs)%>%round(.),p=c(as.vector(xs),true),estimation=c(paste0("est",rep(1:N,each=ntheta)),rep("true",ntheta)))
plotme_p=ggplot(data=ggdf_p,mapping = aes(x=x,y=p,group=estimation))+geom_line(colour = "grey",alpha=0.7)+geom_line(data=ggdf_p%>%filter(estimation=="true"),mapping = aes(x=x,y=p))+ggtitle(paste0("Gamma(2,0.4)[0,10]+Delta_10+Poisson_",ntheta))#+ggtitle("Gamma(2,0.4)[0,10]+Delta_10+Poisson")

return(list(result=res[ind0,],f=plotme_f,p=plotme_p,py=res_py))
}
```

```{r}
pi=0.5
a=0
b=10
theta0=10
nGQ=20
ntheta=100
c=4
```


```{r}
tic=proc.time()
uni=PR_GPP_uni(Xs_bn,a,b,pi,theta0,nGQ,ntheta)
toc=proc.time()
toc-tic
beta=PR_GPP_beta(Xs_bn,a,b,c,pi,theta0,nGQ,ntheta)

BF=uni$py/beta$py

k=c(1,3,20,150)
map_dbl(k,~mean(BF>.x))

hist(BF[BF<=20])
summary(BF)
```


## Permutation Version PPR

```{r}

PPR_GPP_uni=function(Xs_bn,a,b,pi,theta0,nGQ,ntheta){

#permutation
N=nrow(Xs_bn)
n=ncol(Xs_bn)
nP=100
set.seed(123)
ind=sapply(1:nP,function(x){sample.int(n = n,size = n,replace = FALSE)})

#guass.quad
out=gauss.quad(nGQ)
xs_gq=out$nodes*(b-a)/2+(a+b)/2 #change interval
theta=seq(a,b,length.out = ntheta)

## Initial Guess: Uniform on [0,10]
p=rep(1/(b-a)/2,ntheta)
#p=dbeta(x = seq(0,1,length.out = ntheta),shape1 = c,shape2 = c)/(b-a)/2
ind0=ceiling((theta0-a)/((b-a)/ntheta))
p[ind0]=1/2
## weight seq
w=1/(1:n+1)

##Recursion
ppr=function(i,p_0,Xs_bn){
  p=p_0
  xs_bn=Xs_bn[i,]
  Xs_bn_p=sapply(1:nP,function(i){xs_bn[ind[,i]]})

res_t=map(1:nP,function(ix){
  py=0
    for (j in 1:n){
      p_x=map_dbl(theta,~dpois(x = Xs_bn_p[j,ix],lambda = .x))
      int=((b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x = Xs_bn_p[j,ix],lambda = .x))*p[ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-p[ind0]))+p[ind0]*dpois(x = Xs_bn_p[j,ix],lambda = theta0)
  p=(1-w[j])*p+w[j]*p_x*p/int
  py=log(int)+py
    }
    return(list(p=p,py=py))})

pp=sapply(res_t,function(res_t){return(res_t$p)})%>%apply(., 1,mean)
res_py=exp(map_dbl(res_t,~.x$py))%>%mean(.)
return(list(pp=pp,py=res_py))
}

res_t=map(1:N,function(i){return(ppr(i,p,Xs_bn))})
res=sapply(res_t,function(res_t){return(res_t$pp)})
res_py=map_dbl(res_t,~.x$py)




##draw f(theta)
colnames(res)=paste0("est",1:N)
true_f=dtgamma(x_ = theta,shape_ = 2,rate_=0.4,a = a,b=b)*(1-pi)
true_f[ind0]=pi
res_f=res
for (col in 1:ncol(res)){
  res_f[-ind0,col]=(1-res[ind0,col])*res[-ind0,col]
}
ggdf=res_f%>%as_tibble()%>%
  mutate(x=theta,true=true_f)%>%
  gather(data = .,key=estimation,value=p,-x)
plotme_f=ggplot(data=ggdf,mapping = aes(x=x,y=p,group=estimation))+geom_line(colour = "grey",alpha=0.7)+geom_line(data=ggdf%>%filter(estimation=="true"),mapping = aes(x=x,y=p))+ggtitle(paste0("Gamma(2,0.4)[0,10]+Delta_10+Poisson_",c))#+ggtitle("Gamma(2,0.4)[0,10]+Delta_10+Poisson")


## get the p(x) -- Using Guassian Quadratic

Xss=apply(Xs_bn, 1, function(x){x_range(xs_vec = x,ntheta = ntheta,l = 0,u = Inf)})

xs=sapply(1:ntheta,function(j){
  map_dbl(.x = Xss[,j],.f = function(xs_j){
    (b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x=round(xs_j),lambda = .x))*res[,j][ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-res[,j][ind0])+res[,j][ind0]*dpois(x = round(xs_j),lambda = theta0)
  })
  
})

true_xs=x_range(xs_vec = as.vector(Xs_bn),ntheta = ntheta,l = 0,u = Inf)
true=map_dbl(.x = true_xs,
             .f =function(xxs_i){ p=(b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x = round(xxs_i),lambda = .x))*(dtgamma(x_ = theta,shape_ = 2,rate_ = 0.4,a = a,b = b))[ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-pi)+pi*dpois(x = round(xxs_i),lambda = theta0)
             })

ggdf_p=data_frame(x=c(as.vector(Xss),true_xs)%>%round(.),p=c(as.vector(xs),true),estimation=c(paste0("est",rep(1:N,each=ntheta)),rep("true",ntheta)))
plotme_p=ggplot(data=ggdf_p,mapping = aes(x=x,y=p,group=estimation))+geom_line(colour = "grey",alpha=0.7)+geom_line(data=ggdf_p%>%filter(estimation=="true"),mapping = aes(x=x,y=p))+ggtitle(paste0("Gamma(2,0.4)[0,10]+Delta_10+Poisson_",c))#+ggtitle("Gamma(2,0.4)[0,10]+Delta_10+Poisson")


return(list(result=res[ind0,],f=plotme_f,p=plotme_p,py=res_py))
}

PPR_GPP_beta=function(Xs_bn,a,b,c,pi,theta0,nGQ,ntheta){

#permutation
N=nrow(Xs_bn)
n=ncol(Xs_bn)
nP=100
set.seed(123)
ind=sapply(1:nP,function(x){sample.int(n = n,size = n,replace = FALSE)})

#guass.quad
out=gauss.quad(nGQ)
xs_gq=out$nodes*(b-a)/2+(a+b)/2 #change interval
theta=seq(a,b,length.out = ntheta)

## Initial Guess: Uniform on [0,10]
#p=rep(1/(b-a)/2,ntheta)
p=dbeta(x = seq(0,1,length.out = ntheta),shape1 = c,shape2 = c)/(b-a)/2
ind0=ceiling((theta0-a)/((b-a)/ntheta))
p[ind0]=1/2
## weight seq
w=1/(1:n+1)

##Recursion
ppr=function(i,p_0,Xs_bn){
  p=p_0
  xs_bn=Xs_bn[i,]
  Xs_bn_p=sapply(1:nP,function(i){xs_bn[ind[,i]]})

res_t=map(1:nP,function(ix){
  py=0
    for (j in 1:n){
      p_x=map_dbl(theta,~dpois(x = Xs_bn_p[j,ix],lambda = .x))
      int=((b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x = Xs_bn_p[j,ix],lambda = .x))*p[ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-p[ind0]))+p[ind0]*dpois(x = Xs_bn_p[j,ix],lambda = theta0)
  p=(1-w[j])*p+w[j]*p_x*p/int
  py=log(int)+py
    }
    return(list(p=p,py=py))})

pp=sapply(res_t,function(res_t){return(res_t$p)})%>%apply(., 1,mean)
res_py=exp(map_dbl(res_t,~.x$py))%>%mean(.)
return(list(pp=pp,py=res_py))
}

res_t=map(1:N,function(i){return(ppr(i,p,Xs_bn))})
res=sapply(res_t,function(res_t){return(res_t$pp)})
res_py=map_dbl(res_t,~.x$py)




##draw f(theta)
colnames(res)=paste0("est",1:N)
true_f=dtgamma(x_ = theta,shape_ = 2,rate_=0.4,a = a,b=b)*(1-pi)
true_f[ind0]=pi
res_f=res
for (col in 1:ncol(res)){
  res_f[-ind0,col]=(1-res[ind0,col])*res[-ind0,col]
}
ggdf=res_f%>%as_tibble()%>%
  mutate(x=theta,true=true_f)%>%
  gather(data = .,key=estimation,value=p,-x)
plotme_f=ggplot(data=ggdf,mapping = aes(x=x,y=p,group=estimation))+geom_line(colour = "grey",alpha=0.7)+geom_line(data=ggdf%>%filter(estimation=="true"),mapping = aes(x=x,y=p))+ggtitle(paste0("Gamma(2,0.4)[0,10]+Delta_10+Poisson_",c))#+ggtitle("Gamma(2,0.4)[0,10]+Delta_10+Poisson")


## get the p(x) -- Using Guassian Quadratic

Xss=apply(Xs_bn, 1, function(x){x_range(xs_vec = x,ntheta = ntheta,l = 0,u = Inf)})

xs=sapply(1:ntheta,function(j){
  map_dbl(.x = Xss[,j],.f = function(xs_j){
    (b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x=round(xs_j),lambda = .x))*res[,j][ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-res[,j][ind0])+res[,j][ind0]*dpois(x = round(xs_j),lambda = theta0)
  })
  
})

true_xs=x_range(xs_vec = as.vector(Xs_bn),ntheta = ntheta,l = 0,u = Inf)
true=map_dbl(.x = true_xs,
             .f =function(xxs_i){ p=(b-a)/2*sum(out$weights*map_dbl(xs_gq,~dpois(x = round(xxs_i),lambda = .x))*(dtgamma(x_ = theta,shape_ = 2,rate_ = 0.4,a = a,b = b))[ceiling((xs_gq-a)/((b-a)/ntheta))])*(1-pi)+pi*dpois(x = round(xxs_i),lambda = theta0)
             })

ggdf_p=data_frame(x=c(as.vector(Xss),true_xs)%>%round(.),p=c(as.vector(xs),true),estimation=c(paste0("est",rep(1:N,each=ntheta)),rep("true",ntheta)))
plotme_p=ggplot(data=ggdf_p,mapping = aes(x=x,y=p,group=estimation))+geom_line(colour = "grey",alpha=0.7)+geom_line(data=ggdf_p%>%filter(estimation=="true"),mapping = aes(x=x,y=p))+ggtitle(paste0("Gamma(2,0.4)[0,10]+Delta_10+Poisson_",c))#+ggtitle("Gamma(2,0.4)[0,10]+Delta_10+Poisson")


return(list(result=res[ind0,],f=plotme_f,p=plotme_p,py=res_py))
}
```

```{r}
tic=proc.time()
uni_p=PPR_GPP_uni(Xs_bn,a,b,pi,theta0,nGQ,ntheta)
toc=proc.time()
toc-tic
beta_p=PPR_GPP_beta(Xs_bn,a,b,c,pi,theta0,nGQ,ntheta)

#BF=exp(uni$py)/(exp(beta$py))
#mean(BF>1)
BF_p=beta_p$py/uni_p$py
k=c(1,3,20,150)
map_dbl(k,~mean(BF_p>.x))

#hist(BF_p[BF_p<=1])
summary(BF_p)

```

